### ISSUE TITLE
archivefs_dirCache registerFunc path

### ISSUE THREAD

**Issue by wepl** [temisu/WHDLoadArchiveFS#6]
Hi, may specs were unclear...
In the function registerFunc called by archivefs_dirCache I like to get the full path including the name of the actual object. Currently it seems to only return the path without the object. I know the object name is in the fib but having it in the path too makes things simpler.
Could you change it that way?

**Comment by temisu** [comment]
This was easy. Changed. Please see if I got it right

**Comment by wepl** [comment]
Thanks this works fine now :)
