### ISSUE TITLE
archivefs_fileCache/archivefs_dirCache return value

### ISSUE THREAD

**Issue by wepl** [temisu/WHDLoadArchiveFS#7]
Hi again,
can you please change archivefs_fileCache/archivefs_dirCache to return an error code if the the callback function fileFunc/registerFunc has returned 0 for stop (these only return 0 on an error condition).
At the moment it is not really needed to provide a error string for this (but maybe better for completeness)

**Comment by temisu** [comment]
Changed. Please see if this works

**Comment by temisu** [comment]
Changed. Please see if this works

**Comment by wepl** [comment]
Thanks, work fine 👍
